Repository hmcts/civil-general-apps-ccd-definition, pull requests merged in 2023-06, with the labels that each got.

#745 CIV-8888 Fix for navigation issue
  e2e/pages/caseView.page.js
  e2e/steps_file.js
  e2e/tests/ui_tests/1v1GeneralApplicationR2_test.js
  e2e/tests/ui_tests/1v1GeneralApplication_test.js
  e2e/tests/ui_tests/1v1_CP_ApplicationOrders_test.js
  e2e/tests/ui_tests/1v1_CP_HearingNotice_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_ApplicationOrders_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_HearingNotice_AfterSDO_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_ConsentOrders_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-745

#729 CIV-8533 Added API consent order uncloak
  e2e/api/steps.js
  e2e/tests/api_unspec_claim_tests/api_1v1_approve_consent_order_test.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-729

#739 Updating renovate config
  .github/renovate.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-739

#746 CIV-8531 api notify
  e2e/api/steps.js
  e2e/fixtures/ga-ccd/judgeMakeDecision.js
  e2e/tests/api_unspec_claim_tests/api_1v1_approve_consent_order_test.js
  e2e/tests/api_unspec_claim_tests/api_1v1_ga_fee_test.js
  e2e/tests/api_unspec_claim_tests/api_1v1_judge_decision_uncloak_application_test.js
  e2e/tests/api_unspec_claim_tests/api_1v2_defendant_response_offline_nightly_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-746

#764 CIV-0000 Add schedule back
  .github/renovate.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-764

#753 CIV-8933 introducing payment access permissions
  e2e/pages/generalAppCommons.js
  e2e/pages/generalApplication/applicantSummary.page.js
  e2e/steps_file.js
  e2e/tests/ui_tests/1v1GeneralApplicationR2_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js
  ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
  ga-ccd-definition/RoleToAccessProfiles/RoleToAccessProfiles.json
Labels: ns:civil, prd:civil, enableHelm, rel:civil-ga-ccd-pr-753

#741 CIV-7575 api test
  e2e/api/steps.js
  e2e/tests/api_unspec_claim_tests/api_1v1_adjourn_vacate_ga_test.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-741

#740 CIV-8609 Consent Order- Stay the Claim
  charts/civil-ga-ccd/values.elasticsearch.preview.template.yaml
  e2e/api/steps.js
  e2e/fixtures/ga-ccd/nbcAdminTask.js
  e2e/tests/api_unspec_claim_tests/api_1v1_approve_consent_order_test.js
  ga-ccd-definition/CaseEventToComplexTypes/ApproveConsentOrderGAspec.json
  ga-ccd-definition/ComplexTypes/GAApproveConsentOrderGAspec.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-740

#743 CIV-8310 Draft application for scenario with and Without Notice
  e2e/pages/generalApplication/caseFile.page.js
  e2e/pages/generalApplication/claimDocument.page.js
  e2e/pages/generalApplication/judgesJourneyPages/applicationDocument.page.js
  e2e/tests/ui_tests/1v1_CP_ApplicationOrders_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_ConsentOrders_test.js
  ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec.json
  ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json
  ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec.json
  ga-ccd-definition/AuthorisationCaseField/StaffGAspec.json
  ga-ccd-definition/CaseEvent/Camunda/DocmosisEvents.json
  ga-ccd-definition/CaseField/CaseFieldGAspec.json
  ga-ccd-definition/CaseTypeTab/ApplicationDocuments.json
  ga-ccd-definition/FixedLists/DocumentType.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-743

#775 CIV-8310 fix nightly test bug caused by new added ga draft fields
  e2e/api/steps.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-775

#774 CIV-8301 Draft application fix
  e2e/pages/generalApplication/caseFile.page.js
  e2e/pages/generalApplication/claimDocument.page.js
  e2e/pages/generalApplication/judgesJourneyPages/applicationDocument.page.js
  e2e/pages/generalApplication/serviceRequest.page.js
  e2e/steps_file.js
  e2e/tests/ui_tests/1v1GeneralApplication_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_HearingNotice_AfterSDO_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_different_solicitor_GeneralApplication_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/2v1GeneralApplication_test.js
Labels: ns:civil, prd:civil, Testing, rel:civil-ga-ccd-pr-774

#777 CIV-0000 changes to script to avoid duplicate upload
  bin/import-dmn-diagram.sh
  bin/import-wa-bpmn-diagram.sh
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-777

#760 CIV-8430 Rename Adjourn or vacate a hearing
  e2e/fixtures/ga-ccd/createGeneralApplication.js
  e2e/pages/generalApplication/generalApplicationTypes.js
  ga-ccd-definition/FixedLists/GeneralApplicationTypesGAspec.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-760

#770 CIV-8601 Hide uploaded evidence in case file viewer until Application Paid
  e2e/api/steps.js
  e2e/tests/api_unspec_claim_tests/api_1v1_directions_order_test.js
  e2e/tests/ui_tests/1v1GeneralApplicationR2_test.js
  e2e/tests/ui_tests/1v1GeneralApplication_test.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-770

#782 CIV-7590 Cross browser automation
  e2e/run-crossbrowser-tests.sh
  e2e/tests/api_spec_claim_test/api_spec_1v2_afterSDO_GeneralApplication_test.js
  e2e/tests/api_spec_claim_test/api_spec_1v2_move_case_to_caseman_offline_nightly_test.js
  e2e/tests/api_unspec_claim_tests/api_1v1_afterSDO_GeneralApplication_test.js
  e2e/tests/api_unspec_claim_tests/api_1v2_general_app_collections_test.js
  e2e/tests/api_unspec_claim_tests/api_1v2_notify_claim_offline_nightly_test.js
  e2e/tests/api_unspec_claim_tests/api_1v2_proceeds_in_heritage_test.js
  e2e/tests/ui_tests/1v1GeneralApplication_test.js
  e2e/tests/ui_tests/crossBrowser_test.js
  saucelabs.conf.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-782

#772 CIV-8961 Polling Event Emitter
  ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec.json
  ga-ccd-definition/CaseEvent/Camunda/BusinessProcessEvents.json
  ga-ccd-definition/ComplexTypes/BusinessProcessGAspec.json
  ga-ccd-definition/FixedLists/BusinessProcessStatusGAspec.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-772

#784 CIV-9298 code clean
  e2e/fixtures/ga-ccd/judgeMakeDecision.js
  e2e/pages/generalApplication/judgesJourneyPages/makeAnOrder.page.js
  ga-ccd-definition/FixedLists/MakeAppAvailableCheckGAspec.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-784
