Repository hmcts/civil-general-apps-ccd-definition, pull requests merged in 2023-10, with the labels that each got.

#897 CIV-10664 Add missing word in recital text
  e2e/pages/generalAppCommons.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-897

#907 CIV-10926 Update written rep label
  e2e/pages/generalApplication/judgesJourneyPages/drawGeneralOrder.page.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-907

#904 CIV-8301 Fix for nightly pack
  e2e/pages/generalApplication/hearingDetails.page.js
  e2e/pages/generalApplication/judgesJourneyPages/judgesSummary.page.js
  e2e/pages/generalApplication/responseJourneyPages/responseHearingDetails.page.js
  e2e/steps_file.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_same_solicitor_GeneralApplication_test.js
Labels: ns:civil, prd:civil, Testing, rel:civil-ga-ccd-pr-904

#916 CIV-0000 temporary skip of after sdo tests
  e2e/tests/api_unspec_claim_tests/api_1v1_approve_consent_order_test.js
  e2e/tests/ui_tests/multiparty-ga-tests/1v2_CP_HearingNotice_AfterSDO_test.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-916

#899 CIV-10823 new role added for pcq
  bin/add-roles.sh
  src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-899
