Repository hmcts/civil-general-apps-ccd-definition, pull requests merged in 2025-01, with the labels that each got.

#1378 DTSCCI-1364 ccd chart upgrade
  charts/civil-ga-ccd/Chart.yaml
Labels: ns:civil, prd:civil, enable_keep_helm, rel:civil-ga-ccd-pr-1378

#1377 CIV-16361 Add event for GA respondent notification when free app
  ga-ccd-definition/AuthorisationCaseEvent/systemUpdateGAspec-CUI-nonprod.json
  ga-ccd-definition/CaseEvent/Camunda/DashboardEventsGAspec-CUI-nonprod.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1377

#1379 DTSCCI-1400 - skipping failing notify claim details steps
  e2e/tests/api_unspec_claim_tests/api_1v2_notify_claim_details_offline_nightly_test.js
  e2e/tests/api_unspec_claim_tests/api_1v2_notify_claim_offline_nightly_test.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1379

#1381 DTSCCI-000 fix sonar issue
  sonar-project.properties
Labels: ns:civil, prd:civil

#1368 CIV-15643 COSC API Tests
  bin/add-roles.sh
  e2e/api/apiRequest.js
  e2e/api/steps.js
  e2e/fixtures/events/claim/defaultJudgmentSpec.js
  e2e/fixtures/events/claim/judgmentPaidInFull.js
  e2e/fixtures/events/cui/defaultJudgmentCui.js
  e2e/fixtures/events/cui/judgmentPaidInFullCui.js
  e2e/fixtures/featureKeys.js
  e2e/fixtures/ga-ccd/createCoscApplication.js
  e2e/tests/api_spec_claim_test/api_spec_1v1_certificate_of_satisfaction_test.js
  src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1368

#1382 CIV-16410 - Respondent unable to submit response to an urgent application when it's Without Notice to Notice
  ga-ccd-definition/CaseEvent/User/UserEventsGAspec-CUI-nonprod.json
Labels: ns:civil, prd:civil

#1383 CIV-16221 - GA LRvLip - "Vulnerability questions" text should match the font style of the other headings in XUI
  ga-ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json
Labels: ns:civil, prd:civil

#1384 CIV-16376 - Special characters cannot be inputted for email addresses - contact information
  ga-ccd-definition/ComplexTypes/GAHearingDetailsGAspec.json
  ga-ccd-definition/ComplexTypes/GAHearingDetailsRespGAspec.json
Labels: ns:civil, prd:civil

#1386 DTSCCI-1254 - Disable test
  e2e/tests/api_unspec_claim_tests/api_1v1_ga_fee_test.js
Labels: ns:civil, prd:civil

#1387 DTSCCI-1254 - Fixing mixtypeswithvary test
  e2e/tests/api_unspec_claim_tests/api_1v1_ga_fee_test.js
Labels: ns:civil, prd:civil
