Repository hmcts/civil-general-apps-ccd-definition, pull requests merged in 2025-05, with the labels that each got.

#1462 CIV-17094 Fix nightly tests
  e2e/pages/generalApplication/claimDocument.page.js
  e2e/tests/api_unspec_claim_tests/api_1v2_judge_make_final_order_test.js
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1462

#1457 CIV-16855 Amend existing translation WA tasks to direct to WLU (Gen Apps)
  bin/add-roles.sh
  ga-ccd-definition/AuthorisationCaseEvent/AuthorisationCaseEventGAspec-CUI-Welsh-nonprod.json
  ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-Welsh-nonprod.json
  ga-ccd-definition/AuthorisationCaseState/AuthorisationCaseStateGAspec-CUI-Welsh-nonprod.json
  ga-ccd-definition/AuthorisationCaseType/AuthorisationCaseTypeGAspec-CUI-Welsh-nonprod.json
  ga-ccd-definition/FixedLists/TranslatedDocumentType-CUI.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1457

#1470 test: adding the fix for the document count
  e2e/pages/caseView.page.js
  e2e/pages/generalApplication/claimDocument.page.js
Labels: ns:civil, prd:civil, pr-values:elasticsearch, enable_keep_helm, rel:civil-ga-ccd-pr-1470

#1471 CIV-17120 Added two new fields for wa welsh translation task
  ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-nonprod.json
  ga-ccd-definition/CaseEventToFields/EndOfBusinessProcess-CUI-Welsh-nonprod.json
  ga-ccd-definition/CaseField/CaseFieldGAspec-CUI-Welsh-nonprod.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1471

#1480 DTSCCI-2194 Implement Run Failed and Not Executed Functional Tests in Nightly
  Jenkinsfile_nightly
  codecept.conf.js
  e2e/plugins/failedAndNotExecutedTestFilesPlugin.js
  e2e/run-full-functional-tests.sh
  e2e/run-functional-tests.sh
  e2e/run-nightly-functional-tests.sh
  package.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1480

#1481 DTSCCI-2194 Add Properlock File Package and Update Description for Nightly Parameter
  Jenkinsfile_nightly
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1481

#1482 DTSCCI-2238 Only Run Failed And Not Executed Tests Files For Functional Test Stage
  Jenkinsfile_nightly
  codecept.conf.js
  e2e/plugins/failedAndNotExecutedTestFilesPlugin.js
  e2e/run-crossbrowser-tests.sh
  e2e/run-full-functional-tests.sh
  package.json
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1482

#1488 DTSCCI-2243 Add Missing Conversion For .failedTestFiles[] to Nightly
  e2e/run-full-functional-tests.sh
Labels: ns:civil, prd:civil, runFailedTestFiles, rel:civil-ga-ccd-pr-1488
