Repository hmcts/civil-general-apps-ccd-definition, pull requests merged in 2025-04, with the labels that each got.

#1447 DTSCCI-1865 test adding a fix for the spinner to conclude as all tests are fail
  e2e/pages/caseView.page.js
  e2e/pages/generalApplication/gaConfirmation.page.js
  e2e/pages/generalApplication/gaPBANumber.page.js
  e2e/tests/ui_tests/cp_tests/1v1GeneralApplicationR2_test.js
Labels: ns:civil, prd:civil, enable_keep_helm, rel:civil-ga-ccd-pr-1447

#1451 DTSCCI-192 adding missing role
  bin/add-roles.sh
  src/main/java/uk/gov/hmcts/reform/civil/HighLevelDataSetupApp.java
Labels: ns:civil, prd:civil, rel:civil-ga-ccd-pr-1451

#1439 CIV-11074 Add API test Mark Judgment Paid in Full for JBA
  e2e/api/steps.js
  e2e/fixtures/events/claim/claimantResponseSpec.js
  e2e/fixtures/events/claim/requestJudgementSpec.js
  e2e/fixtures/events/cui/defendantResponseCui.js
  e2e/tests/api_spec_claim_test/api_spec_1v1_certificate_of_satisfaction_test.js
Labels: ns:civil, prd:civil, pr-values:elasticsearch, rel:civil-ga-ccd-pr-1439
