Repository hmcts/civil-general-apps-ccd-definition, pull requests merged in 2025-06, with the labels that each got.

#1491 DTSCCI-2243 Remove Run All Tests When There Are No Failed Tests
  codecept.conf.js
  e2e/run-functional-tests.sh
  package.json
Labels: ns:civil, prd:civil, runFailedTestFiles, rel:civil-ga-ccd-pr-1491

#1492 DTSCCI-000 Change Report Name
  package.json
Labels: ns:civil, prd:civil, runFailedTestFiles, rel:civil-ga-ccd-pr-1492

#1493 CIV-16914 added changes pause and delay notifications
  ga-ccd-definition/AuthorisationCaseField/AuthorisationCaseFieldGAspec-CUI-Welsh-nonprod.json
  ga-ccd-definition/CaseEvent/Camunda/DocmosisEvents.json
  ga-ccd-definition/CaseEventToFields/WorkAllocationIntegrationFields-CUI-Welsh-nonprod.json
  ga-ccd-definition/CaseField/CaseFieldGAspec-CUI-Welsh-nonprod.json
  ga-ccd-definition/CaseTypeTab/Documents-CUI-Welsh-nonprod.json
  ga-ccd-definition/FixedLists/PreTranslationGaDocumentType-nonprod.json
Labels: ns:civil, prd:civil, runFailedTestFiles, rel:civil-ga-ccd-pr-1493

#1498 DTSCCI-2086 swtich from jitpack config
  .github/workflows/ado_artifacts_build.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:civil, prd:civil, runFailedTestFiles, rel:civil-ga-ccd-pr-1498

#1496 CIV-16915 - Respond to application - Changes to WA task
  ga-ccd-definition/FixedLists/PreTranslationGaDocumentType-nonprod.json
Labels: ns:civil, prd:civil, runFailedTestFiles, rel:civil-ga-ccd-pr-1496
